version: '3.8'
services:
  holigo-user-service:
    image: holigo/holigo-user-service:1.0.0
    ports:
      - 8081:8081
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@10.1.1.15:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"holigo-user-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"holigo-config-server"},"failFast":true,"username":"","password":""}}},"application":{"name":"holigo-user-service"}}'
    restart: on-failure
    deploy:
      replicas: 2
  holigo-oauth-service:
    image: holigo/holigo-oauth-service
    ports:
      - 8082:8082
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@10.1.1.15:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"holigo-oauth-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"holigo-config-server"},"failFast":true,"username":"","password":""}}},"application":{"name":"holigo-oauth-service"}}'
    restart: on-failure
    deploy:
      replicas: 2
  holigo-otp-service:
    image: holigo/holigo-otp-service:1.0.0
    ports:
      - 8083:8083
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@10.1.1.15:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"holigo-otp-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"holigo-config-server"},"failFast":true,"username":"","password":""}}},"application":{"name":"holigo-otp-service"}}'
    restart: on-failure
    deploy:
      replicas: 2
  holigo-api-gateway-server:
    image: holigo/holigo-api-gateway-server
    ports:
      - 9090:9090
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@10.1.1.15:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"holigo-api-gateway-server"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"holigo-config-server"},"failFast":true,"username":"","password":""}}},"application":{"name":"holigo-api-gateway-server"}}'
    restart: on-failure
    deploy:
      replicas: 2